### ISSUE TITLE
TypeError values.map is not a function

### ISSUE THREAD

**Issue by nagydavid** [nurikk/zigbee2mqtt-frontend#877]
### What happened?

![image](https://user-images.githubusercontent.com/10994218/135115797-d145d0d2-2ac4-4817-bade-247f5a3e98c1.png)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
**Current url**: https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/#/device/0x588e81fffe753241/exposes
**Previous url**: https://home.davikachka.dk/45df7312_zigbee2mqtt


**Error type**: TypeError
**Error message**: values.map is not a function



TypeError: values.map is not a function
    at EnumEditor (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/main.00c7a6f56d7119e5fb75.js:2321:20)
    at Ch (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70045:137)
    at ck (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70155:460)
    at bk (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70138:347)
    at ak (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70138:278)
    at Tj (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70138:138)
    at Lj (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70131:163)
    at https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70011:115
    at exports.unstable_runWithPriority (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqV
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7245453/initialState.json.zip)
BFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:73321:343)
    at gg (https://home.davikachka.dk/api/hassio_ingress/GGDvJb7k-CFjwayWqVBFqTAl815IOWACpU3gWHPZQxc/scripts/vendor.00cfd74d45f5998227f4.js:70010:325)
```

### Did you donwload state.json.zip?

I will attach state.json.zip
[initialState.json.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7245461/initialState.json.zip)

**Comment by nurikk** [comment]
Hi, your're using incorrect converter. your converter has definition

```
 "type": "enum",
  "values": "unoccupied_heating_setpoint"
```
`values` has to be array,ex:

`"values": ["unoccupied_heating_setpoint"]`
